name: update-saas-backend

# Deploy backend only if push on "main"
on:
  push:
    branches: [main, develop, qa, canary]
    paths:
      - "twake/docker/**"
      - "twake/backend/**"
      - ".github/workflows/**"

jobs:
  deploy-php:
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "DOCKERTAGVERSION=2022.Q4.1120" >> $GITHUB_ENV'
      - name: Set env to develop
        if: endsWith(github.ref, '/develop')
        run: 'echo "DOCKERTAG=develop" >> $GITHUB_ENV; echo "DOCKERTAGVERSION=2022.Q4.1120" >> $GITHUB_ENV'
      - name: Set env to develop
        if: endsWith(github.ref, '/qa')
        run: 'echo "DOCKERTAG=qa" >> $GITHUB_ENV; echo "DOCKERTAGVERSION=2022.Q4.1120" >> $GITHUB_ENV'
      - name: Set env to develop
        if: endsWith(github.ref, '/canary')
        run: 'echo "DOCKERTAG=canary" >> $GITHUB_ENV; echo "DOCKERTAGVERSION=${{ env.DOCKERTAGVERSION }}-canary" >> $GITHUB_ENV'
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: 'echo "DOCKERTAG=latest" >> $GITHUB_ENV'
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: twaketech/twake-php
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: twake
          buildoptions: "-t twaketech/twake-php -f docker/twake-php/Dockerfile"
          tags: "${{ env.DOCKERTAG }},${{ env.DOCKERTAGVERSION }}"

  deploy-node:
    runs-on: ubuntu-20.04
    steps:
      - run: 'echo "DOCKERTAGVERSION=2022.Q4.1120" >> $GITHUB_ENV'
      - name: Set env to develop
        if: endsWith(github.ref, '/develop')
        run: 'echo "DOCKERTAG=develop" >> $GITHUB_ENV; echo "DOCKERTAGVERSION=2022.Q4.1120" >> $GITHUB_ENV'
      - name: Set env to develop
        if: endsWith(github.ref, '/qa')
        run: 'echo "DOCKERTAG=qa" >> $GITHUB_ENV; echo "DOCKERTAGVERSION=2022.Q4.1120" >> $GITHUB_ENV'
      - name: Set env to develop
        if: endsWith(github.ref, '/canary')
        run: 'echo "DOCKERTAG=canary" >> $GITHUB_ENV; echo "DOCKERTAGVERSION=${{ env.DOCKERTAGVERSION }}-canary" >> $GITHUB_ENV'
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: 'echo "DOCKERTAG=latest" >> $GITHUB_ENV'
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: twaketech/twake-node
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: twake
          context: .
          target: production
          buildoptions: "-t twaketech/twake-node -f docker/twake-node/Dockerfile"
          tags: "${{ env.DOCKERTAG }},${{ env.DOCKERTAGVERSION }}"
